import type { Locale } from "./types";

export type CardText = {
  name: string;
  type: string;
  description: string;
  ability: string;
  validUse: string;
  target: string;
  effectSummary: string;
  supportCompatibility?: string;
  levelUp?: string;
  additionalEffect?: string;
  weaknessTarget?: string;
  fullEffect?: string;
  offTargetEffect?: string;
  immediateEffect?: string;
  duration?: string;
};

type CardTextByLocale = Record<Locale, CardText>;

export const cardTexts = {
  A001: { th: { name: "สุนัขจอมซน", type: "Animal", description: "สัตว์ป้องกันการกำจัด", ability: "Passive / เมื่อกำลังถูกกำจัด", validUse: "ลงสนามได้เลย", target: "ตัวเอง", effectSummary: "ครั้งแรกที่ถูกนำออกด้วย Weakness: ยกเลิกการกำจัดและห้ามทำคะแนนใน Score Phase ถัดไป" }, en: { name: "Playful Dog", type: "Animal", description: "Removal-protecting animal", ability: "Passive / when being removed", validUse: "Playable directly", target: "Self", effectSummary: "The first time it would be removed by Weakness: cancel the removal and skip scoring in the next Score Phase." } },
  A002: { th: { name: "แมวขี้สงสัย", type: "Animal", description: "สัตว์จัดการการ์ดในมือ", ability: "Trigger / เมื่อได้รับ Support ตรงชนิดครั้งแรก", validUse: "ลงสนามได้เลย", target: "ตัวเอง", effectSummary: "จั่ว 1 ใบ แล้วเลือกการ์ดจากมือ 1 ใบวางใต้สุดของ Deck" }, en: { name: "Curious Cat", type: "Animal", description: "Hand-management animal", ability: "Trigger / first matching Support", validUse: "Playable directly", target: "Self", effectSummary: "Draw 1 card, then put 1 card from hand on the bottom of the Deck." } },
  A003: { th: { name: "กระต่ายว่องไว", type: "Animal", description: "สัตว์ป้องกันการลด Level", ability: "Passive / เมื่อกำลังถูกลด Level", validUse: "ลงสนามได้เลย", target: "ตัวเอง", effectSummary: "ครั้งแรกต่อการลงสนาม ยกเลิกการลด Level และไม่ทิ้ง Support" }, en: { name: "Swift Rabbit", type: "Animal", description: "Level-loss protector", ability: "Passive / when about to lose Level", validUse: "Playable directly", target: "Self", effectSummary: "The first time it would lose Level after entering play: cancel the Level loss and keep attached Support." } },
  A004: { th: { name: "หมีใจดี", type: "Animal", description: "สัตว์รักษา Support", ability: "Passive / เมื่อ Support จะถูกทิ้งด้วย Weakness", validUse: "ลงสนามได้เลย", target: "ตัวเอง", effectSummary: "ครั้งแรกต่อการลงสนาม ยกเลิกการทิ้ง Support และหมีห้ามทำคะแนนใน Score Phase ถัดไปแทน" }, en: { name: "Gentle Bear", type: "Animal", description: "Support-saving animal", ability: "Passive / when Support would be discarded by Weakness", validUse: "Playable directly", target: "Self", effectSummary: "The first time per entry: prevent a Support from being discarded, but the Bear skips scoring in the next Score Phase." } },
  A005: { th: { name: "นกส่งข่าว", type: "Animal", description: "สัตว์ควบคุมการจั่ว", ability: "On Play / เมื่อลงสนาม", validUse: "ลงสนามได้เลย", target: "Deck ของตนเอง", effectSummary: "ดูการ์ดใบบนสุดของ Deck แล้วเลือกวางกลับด้านบนหรือย้ายไปใต้สุด" }, en: { name: "Messenger Bird", type: "Animal", description: "Deck-control animal", ability: "On Play / when it enters play", validUse: "Playable directly", target: "Own Deck", effectSummary: "Look at the top card of your Deck and choose to keep it on top or move it to the bottom." } },
  A006: { th: { name: "ปลาจอมพลัง", type: "Animal", description: "สัตว์เร่งคะแนน", ability: "Trigger / Score Phase แรกหลังลงสนาม", validUse: "ลงสนามได้เลย", target: "คะแนนของตนเอง", effectSummary: "ครั้งแรกที่สร้างคะแนนหลังลงสนาม ได้คะแนนเพิ่ม +1" }, en: { name: "Energetic Fish", type: "Animal", description: "Score-boosting animal", ability: "Trigger / first Score Phase after entering play", validUse: "Playable directly", target: "Your score", effectSummary: "The first time it scores after entering play, gain +1 extra score." } },
  A007: { th: { name: "เต่าเกราะแข็ง", type: "Animal", description: "สัตว์รักษาการทำคะแนน", ability: "Passive / เมื่อกำลังถูกห้ามทำคะแนน", validUse: "ลงสนามได้เลย", target: "ตัวเอง", effectSummary: "ครั้งแรกต่อการลงสนาม ยกเลิกสถานะห้ามทำคะแนน", supportCompatibility: "รับผลรองของ Support ได้ แต่ Support ในชุดนี้ไม่เพิ่ม Level ให้เต่า" }, en: { name: "Armored Turtle", type: "Animal", description: "Score-protection animal", ability: "Passive / when about to be prevented from scoring", validUse: "Playable directly", target: "Self", effectSummary: "The first time per entry: cancel the cannot-score effect.", supportCompatibility: "Can still receive secondary Support effects, but no Support in this set increases the Turtle's Level." } },
  A008: { th: { name: "ลิงจอมเจ้าเล่ห์", type: "Animal", description: "สัตว์นำ Support กลับมาใช้", ability: "On Play / เมื่อลงสนาม", validUse: "ลงสนามได้เลย", target: "Support ฝ่ายตนเอง", effectSummary: "เลือก Support 1 ใบที่ติดกับ Animal ของตนเอง นำกลับขึ้นมือ; Animal ที่เสีย Support ลด Level 1 หาก Support เคยเพิ่ม Level", supportCompatibility: "รับผลรองของ Support ได้ แต่ Support ในชุดนี้ไม่เพิ่ม Level ให้ลิง" }, en: { name: "Clever Monkey", type: "Animal", description: "Support-recycling animal", ability: "On Play / when it enters play", validUse: "Playable directly", target: "Own attached Support", effectSummary: "Return 1 attached Support to hand; the Animal that lost that Support loses 1 Level if the Support had increased Level.", supportCompatibility: "Can receive secondary Support effects, but no Support in this set increases the Monkey's Level." } },
  S001: { th: { name: "กระดูกแสนอร่อย", type: "Support", description: "การ์ดเพิ่ม Level / ป้องกันการนำออก", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตนเอง", target: "Animal ฝ่ายตนเอง", effectSummary: "ใช้กับสุนัข: +1 Level และติดไว้; ครั้งถัดไปที่ถูกกำจัดหรือเด้งขึ้นมือ ให้ยกเลิก แล้วทิ้งการ์ดนี้และลด Level 1", supportCompatibility: "ตรงชนิด: สุนัข", levelUp: "+1 Level", additionalEffect: "ป้องกันการกำจัดหรือเด้งขึ้นมือ 1 ครั้ง" }, en: { name: "Delicious Bone", type: "Support", description: "Level-up / removal shield", ability: "Action Phase", validUse: "Use on one of your Animals", target: "Own Animal", effectSummary: "On a Dog: +1 Level and attach; the next time it would be removed or returned to hand, cancel it, discard this card, and lose 1 Level.", supportCompatibility: "Matching type: Dog", levelUp: "+1 Level", additionalEffect: "Prevents one removal or bounce" } },
  S002: { th: { name: "ไหมพรมหลากสี", type: "Support", description: "การ์ดเพิ่ม Level / ควบคุม Deck", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตนเอง", target: "Animal ฝ่ายตนเอง", effectSummary: "ใช้กับแมว: +1 Level, ดูใบบนสุดแล้วเลือกคงไว้หรือส่งใต้ Deck, จากนั้นติดไว้", supportCompatibility: "ตรงชนิด: แมว", levelUp: "+1 Level", additionalEffect: "ดูใบบนสุดแล้วจัดการตำแหน่งการ์ด" }, en: { name: "Colorful Yarn", type: "Support", description: "Level-up / deck control", ability: "Action Phase", validUse: "Use on one of your Animals", target: "Own Animal", effectSummary: "On a Cat: +1 Level, look at the top card and choose to keep it there or put it on the bottom of the Deck, then attach.", supportCompatibility: "Matching type: Cat", levelUp: "+1 Level", additionalEffect: "Look at the top card and reposition it" } },
  S003: { th: { name: "แครอทสด", type: "Support", description: "การ์ดเพิ่ม Level / ป้องกันลด Level", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตนเอง", target: "Animal ฝ่ายตนเอง", effectSummary: "ใช้กับกระต่าย: +1 Level และป้องกันการลด Level ถึงจบเทิร์นถัดไปของคู่ต่อสู้; ติดไว้", supportCompatibility: "ตรงชนิด: กระต่าย", levelUp: "+1 Level", additionalEffect: "ป้องกันการลด Level ชั่วคราว" }, en: { name: "Fresh Carrot", type: "Support", description: "Level-up / level-loss protection", ability: "Action Phase", validUse: "Use on one of your Animals", target: "Own Animal", effectSummary: "On a Rabbit: +1 Level and prevent Level loss until the end of the opponent's next turn; attach.", supportCompatibility: "Matching type: Rabbit", levelUp: "+1 Level", additionalEffect: "Temporary Level-loss immunity" } },
  S004: { th: { name: "น้ำผึ้งหวาน", type: "Support", description: "การ์ดเพิ่ม Level / คงคะแนนขั้นต่ำ", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตนเอง", target: "Animal ฝ่ายตนเอง", effectSummary: "ใช้กับหมี: +1 Level; ถ้าจะทำ 0 คะแนนใน Score Phase ถัดไป ให้ทำ 1 คะแนนแทน; ติดไว้", supportCompatibility: "ตรงชนิด: หมี", levelUp: "+1 Level", additionalEffect: "รักษาคะแนนขั้นต่ำ 1 ใน Score Phase ถัดไป" }, en: { name: "Sweet Honey", type: "Support", description: "Level-up / minimum score floor", ability: "Action Phase", validUse: "Use on one of your Animals", target: "Own Animal", effectSummary: "On a Bear: +1 Level; if it would score 0 in the next Score Phase, it scores 1 instead; attach.", supportCompatibility: "Matching type: Bear", levelUp: "+1 Level", additionalEffect: "Keeps next score at least 1" } },
  S005: { th: { name: "เมล็ดพืชชั้นดี", type: "Support", description: "การ์ดเพิ่ม Level / หมุนเวียนมือ", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตนเอง", target: "Animal ฝ่ายตนเอง", effectSummary: "ใช้กับนก: +1 Level, จั่ว 1 แล้ววางการ์ดจากมือ 1 ใบใต้ Deck; ติดไว้", supportCompatibility: "ตรงชนิด: นก", levelUp: "+1 Level", additionalEffect: "จั่ว 1 แล้วส่ง 1 ใบใต้ Deck" }, en: { name: "Premium Seeds", type: "Support", description: "Level-up / hand cycling", ability: "Action Phase", validUse: "Use on one of your Animals", target: "Own Animal", effectSummary: "On a Bird: +1 Level, draw 1 and put 1 card from hand on the bottom of the Deck; attach.", supportCompatibility: "Matching type: Bird", levelUp: "+1 Level", additionalEffect: "Draw 1 then bottom 1" } },
  S006: { th: { name: "อาหารปลาพิเศษ", type: "Support", description: "การ์ดเพิ่ม Level / ป้องกัน Weakness", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตนเอง", target: "Animal ฝ่ายตนเอง", effectSummary: "ใช้กับปลา: +1 Level และไม่เป็นเป้าหมาย Weakness ถึงจบเทิร์นถัดไปของคู่ต่อสู้; ติดไว้", supportCompatibility: "ตรงชนิด: ปลา", levelUp: "+1 Level", additionalEffect: "กัน Weakness ชั่วคราว" }, en: { name: "Special Fish Food", type: "Support", description: "Level-up / Weakness immunity", ability: "Action Phase", validUse: "Use on one of your Animals", target: "Own Animal", effectSummary: "On a Fish: +1 Level and cannot be targeted by Weakness until the end of the opponent's next turn; attach.", supportCompatibility: "Matching type: Fish", levelUp: "+1 Level", additionalEffect: "Temporary Weakness immunity" } },
  W001: { th: { name: "ที่ครอบปาก", type: "Weakness", description: "จุดอ่อนของสุนัข", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตรงข้าม", target: "สัตว์ที่แพ้ทาง: สุนัข", effectSummary: "ตรงชนิด: Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ; Level 1 นำออกจากสนาม", weaknessTarget: "สุนัข", fullEffect: "Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ", offTargetEffect: "คะแนนของ Animal เป้าหมายใน Score Phase ถัดไป -1 (ต่ำสุด 0)" }, en: { name: "Muzzle", type: "Weakness", description: "Dog weakness", ability: "Action Phase", validUse: "Use on an opponent Animal", target: "Weak target: Dog", effectSummary: "Matching target: Level 2–3 loses 1 Level and discards 1 Level-increasing Support; Level 1 is removed from the board.", weaknessTarget: "Dog", fullEffect: "Level 2–3 loses 1 Level and discards 1 Level-increasing Support", offTargetEffect: "The target's score in the next Score Phase is reduced by 1 (minimum 0)" } },
  W002: { th: { name: "เลเซอร์พอยน์เตอร์", type: "Weakness", description: "จุดอ่อนของแมว", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตรงข้าม", target: "สัตว์ที่แพ้ทาง: แมว", effectSummary: "ตรงชนิด: Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ; Level 1 นำออกจากสนาม", weaknessTarget: "แมว", fullEffect: "Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ", offTargetEffect: "คะแนนของ Animal เป้าหมายใน Score Phase ถัดไป -1 (ต่ำสุด 0)" }, en: { name: "Laser Pointer", type: "Weakness", description: "Cat weakness", ability: "Action Phase", validUse: "Use on an opponent Animal", target: "Weak target: Cat", effectSummary: "Matching target: Level 2–3 loses 1 Level and discards 1 Level-increasing Support; Level 1 is removed from the board.", weaknessTarget: "Cat", fullEffect: "Level 2–3 loses 1 Level and discards 1 Level-increasing Support", offTargetEffect: "The target's score in the next Score Phase is reduced by 1 (minimum 0)" } },
  W003: { th: { name: "กับดักบนพื้น", type: "Weakness", description: "จุดอ่อนของกระต่ายและหมี", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตรงข้าม", target: "สัตว์ที่แพ้ทาง: กระต่าย / หมี", effectSummary: "ตรงชนิด: Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ; Level 1 นำออกจากสนาม", weaknessTarget: "กระต่ายและหมี", fullEffect: "Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ", offTargetEffect: "คะแนนของ Animal เป้าหมายใน Score Phase ถัดไป -1 (ต่ำสุด 0)" }, en: { name: "Ground Trap", type: "Weakness", description: "Rabbit and Bear weakness", ability: "Action Phase", validUse: "Use on an opponent Animal", target: "Weak target: Rabbit / Bear", effectSummary: "Matching target: Level 2–3 loses 1 Level and discards 1 Level-increasing Support; Level 1 is removed from the board.", weaknessTarget: "Rabbit and Bear", fullEffect: "Level 2–3 loses 1 Level and discards 1 Level-increasing Support", offTargetEffect: "The target's score in the next Score Phase is reduced by 1 (minimum 0)" } },
  W004: { th: { name: "กรงนก", type: "Weakness", description: "จุดอ่อนของนก", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตรงข้าม", target: "สัตว์ที่แพ้ทาง: นก", effectSummary: "ตรงชนิด: Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ; Level 1 นำออกจากสนาม", weaknessTarget: "นก", fullEffect: "Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ", offTargetEffect: "คะแนนของ Animal เป้าหมายใน Score Phase ถัดไป -1 (ต่ำสุด 0)" }, en: { name: "Bird Cage", type: "Weakness", description: "Bird weakness", ability: "Action Phase", validUse: "Use on an opponent Animal", target: "Weak target: Bird", effectSummary: "Matching target: Level 2–3 loses 1 Level and discards 1 Level-increasing Support; Level 1 is removed from the board.", weaknessTarget: "Bird", fullEffect: "Level 2–3 loses 1 Level and discards 1 Level-increasing Support", offTargetEffect: "The target's score in the next Score Phase is reduced by 1 (minimum 0)" } },
  W005: { th: { name: "เบ็ดตกปลา", type: "Weakness", description: "จุดอ่อนของปลา", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตรงข้าม", target: "สัตว์ที่แพ้ทาง: ปลา", effectSummary: "ตรงชนิด: Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ; Level 1 นำออกจากสนาม", weaknessTarget: "ปลา", fullEffect: "Level 2–3 ลด 1 Level และทิ้ง Support ที่เพิ่ม Level 1 ใบ", offTargetEffect: "คะแนนของ Animal เป้าหมายใน Score Phase ถัดไป -1 (ต่ำสุด 0)" }, en: { name: "Fishing Hook", type: "Weakness", description: "Fish weakness", ability: "Action Phase", validUse: "Use on an opponent Animal", target: "Weak target: Fish", effectSummary: "Matching target: Level 2–3 loses 1 Level and discards 1 Level-increasing Support; Level 1 is removed from the board.", weaknessTarget: "Fish", fullEffect: "Level 2–3 loses 1 Level and discards 1 Level-increasing Support", offTargetEffect: "The target's score in the next Score Phase is reduced by 1 (minimum 0)" } },
  X001: { th: { name: "เพลงกล่อมหลับ", type: "Special", description: "หยุดคะแนน 1 รอบ", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตรงข้าม", target: "Animal ฝ่ายตรงข้าม", effectSummary: "ห้ามสร้างคะแนนใน Score Phase ถัดไป", immediateEffect: "ห้ามสร้างคะแนน", duration: "ถึง Score Phase ถัดไป" }, en: { name: "Lullaby", type: "Special", description: "Skip one scoring round", ability: "Action Phase", validUse: "Use on an opponent Animal", target: "Opponent Animal", effectSummary: "The target cannot score in the next Score Phase.", immediateEffect: "Prevents scoring", duration: "Until the next Score Phase" } },
  X002: { th: { name: "เกราะป้องกันจุดอ่อน", type: "Special", description: "Reaction ป้องกัน Weakness", ability: "Reaction / เมื่อถูกใช้ Weakness", validUse: "ใช้เมื่อกำลังถูกเล่นใส่ด้วย Weakness", target: "Weakness ที่กำลัง Resolve", effectSummary: "ยกเลิก Weakness Card ที่กำลังใช้กับ Animal ของคุณ แล้วทิ้ง Weakness ใบนั้น", immediateEffect: "ยกเลิก Weakness", duration: "ล็อก Utility 1 เทิร์นถัดไป" }, en: { name: "Weakness Shield", type: "Special", description: "Reaction that blocks Weakness", ability: "Reaction / when targeted by Weakness", validUse: "Use while a Weakness is resolving against your Animal", target: "Resolving Weakness", effectSummary: "Cancel the Weakness being played on your Animal and discard that Weakness card.", immediateEffect: "Cancels Weakness", duration: "Locks Utility for your next turn" } },
  X003: { th: { name: "เปลี่ยนตัวด่วน", type: "Special", description: "เปลี่ยน Animal", ability: "Action Phase", validUse: "ใช้กับ Animal ฝ่ายตนเอง", target: "Animal ฝ่ายตนเอง", effectSummary: "นำ Animal ของคุณ 1 ตัวกลับมือ; Support ทั้งหมดทิ้ง; ลง Animal จากมือ 1 ใบในช่องเดิมโดยไม่ใช้สิทธิ์ลง Animal ปกติ", immediateEffect: "สลับ Animal", duration: "Animal ใหม่ยังไม่ทำคะแนนจนถึงเทิร์นถัดไป" }, en: { name: "Quick Swap", type: "Special", description: "Swap your Animal", ability: "Action Phase", validUse: "Use on one of your Animals", target: "Own Animal", effectSummary: "Return 1 of your Animals to hand; discard all attached Support; play 1 Animal from hand into the same slot without spending the normal Animal play.", immediateEffect: "Swaps Animals", duration: "The new Animal does not score until your next turn" } },
  X004: { th: { name: "ลมแรงพัดปลิว", type: "Special", description: "นำ Animal Level 1 ขึ้นมือ", ability: "Action Phase", validUse: "ใช้กับ Animal Level 1 ฝ่ายตรงข้าม", target: "Animal Level 1 ฝ่ายตรงข้าม", effectSummary: "เลือก Animal Level 1 ฝ่ายตรงข้าม 1 ตัว นำกลับขึ้นมือ; Support ที่ติดทั้งหมดทิ้ง", immediateEffect: "ส่ง Animal Level 1 กลับมือ", duration: "ใช้กับ Level 2–3 ไม่ได้" }, en: { name: "Strong Wind", type: "Special", description: "Return a Level 1 Animal to hand", ability: "Action Phase", validUse: "Use on an opponent Level 1 Animal", target: "Opponent Level 1 Animal", effectSummary: "Choose 1 opponent Level 1 Animal and return it to hand; discard all attached Support.", immediateEffect: "Returns Level 1 Animal to hand", duration: "Cannot target Level 2–3" } },
  X005: { th: { name: "ขโมยอาหาร", type: "Special", description: "พลิกคะแนน", ability: "Action Phase", validUse: "ใช้เมื่อคะแนนคุณน้อยกว่าคู่ต่อสู้", target: "คะแนนผู้เล่นทั้งสอง", effectSummary: "คู่ต่อสู้ -1 คะแนน และคุณ +1 คะแนน", immediateEffect: "สลับคะแนนบางส่วน", duration: "คะแนนต่ำสุด 0" }, en: { name: "Food Thief", type: "Special", description: "Flip the score gap", ability: "Action Phase", validUse: "Use when your score is lower than the opponent's", target: "Both players' scores", effectSummary: "The opponent loses 1 score and you gain 1 score.", immediateEffect: "Shifts score by 1", duration: "Score cannot go below 0" } }
} as Record<string, CardTextByLocale>;

const FALLBACK_CARD: CardText = {
  name: "Unknown Card",
  type: "Unknown",
  description: "",
  ability: "",
  validUse: "",
  target: "",
  effectSummary: "",
};

export function getLocalizedCard(cardId: string, locale: Locale): CardText {
  const entry = cardTexts[cardId];
  if (!entry) {
    return { ...FALLBACK_CARD, name: `Unknown Card (${cardId})` };
  }
  const text = entry[locale] ?? entry.th;
  if (!text) {
    return { ...FALLBACK_CARD, name: `Unknown Card (${cardId})` };
  }
  return text;
}

/** @deprecated Use `getLocalizedCard` instead. */
export function getCardText(cardId: string, locale: Locale): CardText {
  return getLocalizedCard(cardId, locale);
}
